controller_manager:
  ros__parameters:
    update_rate: 20
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 20.0 # You can set this higher than the controller manager update rate, but it will be throttled

    base_frame_id: base_footprint

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.196666 # from solidwork wheel origin*2. အစဥ်မပြေ
    wheel_radius: 0.0500     # solidwork wheel diameter is 0.1 m

    # အထက်ပါတွက်ချက်မှုအရ robot သည် 

    use_stamped_vel: false

    # open_loop: false    wheel_separation: 0.1966

    # wheels_per_side: x
    wheel_separation_multiplier: 1.000  # ဒါကသိပ်မထူးဘူး။ မူလ source code မှာ ယူမထားတာ ဒါမှမဟုတ် နဲနဲပဲယူထားတာဖြစ်နိုင်တယ်။ 
    left_wheel_radius_multiplier: 0.986096046
    right_wheel_radius_multiplier: 0.98804466

    odom_frame_id: odom
    enable_odom_tf: true
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    # odom_frame_id: x
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    # open_loop: x
    # enable_odom_tf: x

    # cmd_vel_timeout: x
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x
    

    # linear.x.has_velocity_limits: false
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: NAN
    # linear.x.min_velocity: NAN
    # linear.x.max_acceleration: NAN
    # linear.x.min_acceleration: NAN
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    # angular.z.has_velocity_limits: false
    # angular.z.has_acceleration_limits: false
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: NAN
    # angular.z.min_velocity: NAN
    # angular.z.max_acceleration: NAN
    # angular.z.min_acceleration: NAN
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: NAN




# joint_broad:
#   ros__parameters: